ktor:
  deployment:
    port: 8080
  #    grpcPort: 8081
  application:
    startup: concurrent
    modules:
      - io.appium.multiplatform.server.ApplicationKt.module
      - io.appium.multiplatform.server.PluginKt.configureContentNegotiation
      - io.appium.multiplatform.server.PluginKt.configureRequestValidation
      - io.appium.multiplatform.server.PluginKt.configureCallLogging
      - io.appium.multiplatform.server.PluginKt.configureAutoHeadResponse
      - io.appium.multiplatform.server.PluginKt.configureCORS
      - io.appium.multiplatform.server.PluginKt.configureDefaultHeaders
      - io.appium.multiplatform.server.PluginKt.configureForwardedHeaders
      - io.appium.multiplatform.server.PluginKt.configureMicrometerMetrics
      - io.appium.multiplatform.server.PluginKt.configureCachingHeaders
      - io.appium.multiplatform.server.PluginKt.configureCompression
      - io.appium.multiplatform.server.PluginKt.configureConditionalHeaders
      - io.appium.multiplatform.server.PluginKt.configurePartialContent
      - io.appium.multiplatform.server.PluginKt.configStatusPages
#      - io.appium.multiplatform.server.PluginKt.configureSessions
